# version: '2.1'
#
# services:
#
#   db:
#     image: mysql:5.7
#     restart: unless-stopped
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: yes
#       MYSQL_DATABASE: ${DB_DATABASE}
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#       SERVICE_NAME: mysql
#
#   # nginx:
#   #   image: nginx:alpine
#   #   container_name: travellist-nginx
#   #   restart: unless-stopped
#   #   ports:
#   #     - 8000:80
#   #   volumes:
#   #     - ./:/var/www
#   #     - ./docker-compose/nginx:/etc/nginx/conf.d/
#   #   networks:
#   #     - travellist
#
#   laravel:
#     image: docker.io/bitnami/laravel:7
#     ports:
#       - '8080:3000'
#     env_file: .env
#     volumes:
#       - '.:/app'
#     depends_on:
#       - db
#
#
version: "3.8"

networks:
  app-network:
    driver: local

volumes:
  dbdata:

services:
  server:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 81:80
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mysql:5.7.33
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: emi_simulador
    networks:
      - app-network
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql

  app:
    build: .
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./:/var/www
    depends_on:
      - db

  node:
    image: node:15-alpine
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    command: sh /var/www/node_start.sh
    depends_on:
      - app
